name: capstone_design
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: 4.10.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^12.0.0+1
  image_picker: ^0.8.7
  scan: ^1.6.0
  lucide_icons: ^0.257.0
  fl_chart: ^0.65.0
  google_maps_flutter: ^2.12.0
  location: ^8.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  http: ^0.13.0
  dio: ^5.8.0+1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/img/splash_logo.png
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
